name: Java CI/CD to Docker Hub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/wiki-service
      TAG: ${{ github.sha }}

    steps:
      # 1. Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Java environment
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'  # Cache Maven dependencies for faster builds

      # 3. Run all tests
      - name: Run tests
        run: mvn test

      # 4. Package application
      - name: Package application
        run: mvn clean package -DskipTests

      # 5. Login Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Build Docker image
      - name: Build Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ env.TAG }}
          docker tag ${{ env.IMAGE_NAME }}:${{ env.TAG }} ${{ env.IMAGE_NAME }}:latest

      # 7. Push image to Docker Hub
      - name: Push Docker images
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ env.TAG }}
          docker push ${{ env.IMAGE_NAME }}:latest

      # 8. Checkout ArgoCD config repo
      - name: Checkout config repo
        uses: actions/checkout@v4
        with:
          repository: yijun-l/wiki-config
          token: ${{ secrets.WIKI_CONFIG_PAT }}
          path: config-repo

      # 9. Update Deployment image in config repo
      - name: Update Deployment image
        run: |
          echo "Before change:"
          cat config-repo/environments/dev/values.yaml
          sed -i "s|tag: .*|tag: ${{ env.TAG }}|g" config-repo/environments/dev/values.yaml
          echo "After change:"
          cat config-repo/environments/dev/values.yaml

      # check token
      - name: Debug secret
        run: |
          if [ -z "${{ secrets.WIKI_CONFIG_PAT }}" ]; then
            echo "Secret WIKI_CONFIG_PAT is empty!"
          else
            echo "Secret WIKI_CONFIG_PAT is set"
          fi
      # 10. Commit & push changes to config repo
      - name: Commit & push
        run: |
          cd config-repo
          
          echo "Repo status before commit:"
          git status
          
          echo "Remote:"
          git remote -v
      
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update image to ${{ env.TAG }}"
          git push origin main